name: gwasstudio
channels:
  - conda-forge
  - nodefaults
dependencies:
  - mamba
  - pip  # pip must be mentioned explicitly, or conda-lock will fail
  - poetry-core=2.1.*
  - poetry=2.*
  - make
  - mongodb
  - mongo-tools
  - dash-bio
