name: gwasstudio
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10.*  # or don't specify the version and use the latest stable Python
  - pip  # pip must be mentioned explicitly, or conda-lock will fail
  - poetry=2.*
  - tiledb-py=0.33.*

# Non-standard section listing target platforms for conda-lock:
platforms:
  - linux-64
