name: gwasstudio
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12.*  # or don't specify the version and use the latest stable Python
  - mamba
  - pip  # pip must be mentioned explicitly, or conda-lock will fail
  - poetry=2.*
  - make
