# MongoDB connection
mdbc:
  # local
  uri: "mongodb://localhost:27018/cdh"
  # remote
#  uri: "mongodb://username:password@hostname:27017/dbname?authSource=dbname"

# Ancestry list
# https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5815218/table/Tab1/?report=objectonly
ancestry:
  - "Aboriginal Australian"
  - "African American or Afro-Caribbean"
  - "African unspecified"
  - "Asian unspecified"
  - "Central Asian"
  - "East Asian"
  - "European"
  - "Greater Middle Eastern (Middle Eastern, North African, or Persian)"
  - "Hispanic or Latin American"
  - "Icelandic"
  - "NR"
  - "Native American"
  - "Oceanian"
  - "Other"
  - "Other admixed ancestry"
  - "South Asian"
  - "South East Asian"
  - "Sub-Saharan African"

# Genome build list
build:
  - "GRCh37"
  - "GRCh38"

# Data category list
data_category:
  - "GWAS"
  - "pQTL"
  - "eQTL"
  - "Single-cell"
  - "scientific_article"

# Hashing
hashing:
  algorithm: "sha256"
  length: 10

# TileDB configuration
# https://cloud.tiledb.com/academy/structure/arrays/tutorials/basics/configuration/index.html
tiledb_sm_config:
  "sm.dedup_coords": 'true'
