# MongoDB connection
mdbc:
  # local
  uri: "mongodb://localhost:27018/cdh"
  # remote
#  uri: "mongodb://username:password@hostname:27017/dbname?authSource=dbname"

# Ancestry groups
# https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5815218/table/Tab1/?report=objectonly
ancestry_groups:
  AUS: Aboriginal Australian
  AFA: African American or Afro-Caribbean
  AFR: African unspecified
  ASN: Asian unspecified
  CAS: Central Asian
  EAS: East Asian
  EUR: European
  MDE: Greater Middle Eastern (Middle Eastern, North African, or Persian)
  AMR: Hispanic or Latin American
  NR: Not reported / unknown
  NAM: Native American
  OCE: Oceanian
  OTH: Other
  ADM: Other admixed ancestry
  SAS: South Asian
  SEA: South East Asian
  SAF: Sub-Saharan African

# Genome build list
build:
  - "GRCh37"
  - "GRCh38"

# Data category list
data_category:
  - "GWAS"
  - "pQTL"
  - "eQTL"
  - "Single-cell"
  - "scientific_article"

# Hashing
hashing:
  algorithm: "sha256"
  length: 10

# TileDB configuration
# https://cloud.tiledb.com/academy/structure/arrays/tutorials/basics/configuration/index.html
tiledb_sm_config:
  "sm.dedup_coords": 'false'
