name: test

on: [push,pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Clear conda cache
        run: conda clean --all -y

      - uses: conda-incubator/setup-miniconda@v4
        with:
          use-mamba: true
          activate-environment: gwasstudio
          environment-file: base_environment_docker.yml
          auto-update-conda: true
          auto-activate-base: false
          python-version: ${{ matrix.python-version }}
          channels: conda-forge
          channel-priority: true
        env:
          CONDA_NO_PLUGINS: "true"

      - name: Install the project
        shell: bash -el {0}
        run: |
          make dependencies_dev
          make install

      - name: Test version
        shell: bash -el {0}
        run: |
          make test
